travis:
  secure:
    BINSTAR_TOKEN: eT2rDp5CiVekl+ArBfdPPlHyFEOyctcWSdJTh/rPvbdGGGNuZ8g0XhWKj+4djPGtlOr+uapVj4wuNz9+rE5htP63fI72bavgrzdF97Mc+FCwfJfidEsxD2Vo0zyblOM/Heii86ANQ+AXrqbpKdJhtnZLqBDqxXkqJLlSqTZZeU9RXg50d5lg9afMZ8qD/tZg/iuaWmK08EodP/kaJTAXJJjZnZUnEZFPbiAG61lzfKP//y5H/uJhDYUj+reHFbBrW8H3tmCGUjwc8YOxjVr9sVGo8k8eSWq2fL5eMba3jdREtEqy/h16T7tL9ABGZwQBzAQ/S2fpRzyrqKhiY4VA34VlhkO9JFVRdF23g8Ki05HJoy0vE2Zf6ItfMgJo+FvvwKytJqrWlM/Xi4Xk4i65jaSXv2qiCqUFdSL1nI1lfslr2pEVYuQG1wqsRY5vol5+pIhbC0lq5kcnCk+MNP9I8Uf2/fP+wY+sOgki+Cs8Sq0xv1rxwFqlarS+KZMVLHS+wDblAkfPouQ/VPtkG4Uq5DF3kdSZH8PxjabIXpEvehoXDD5qWNaj4D/n5/WQo4uKY1sx9pFYKsMcxOSGhmmxvcYmJhaVL52hLw1c/NP1AxtpIMafPoIDUZ7XqPkhIF2JbuPCWKMxXDS2ky+Jm36c73IBFodrxtrBgpsL0BD/Xuc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
